### ISSUE TITLE
Ask Paul for `blind` option suitable for blind submissions

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#10]
@andygill are you OK with this?

**Comment by nrnrnr** [comment]
Dammit, I am sad that this is postponed to Fall 2015...  I wanted to get this in so I could put it in a demo for Steve Blackburn

**Comment by MatthewFluet** [comment]
Closing, as the `sigplanconf.cls` file has been retired, and the repository will be archived.
