### ISSUE TITLE
Title banner is not displayed on legacy paper

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#17]
I formatted a legacy paper from 2011.  It works OK except that the title banner is not displayed.

**Comment by andygill** [comment]
Is this a `reprint` option problem? #19 ?

**Comment by nrnrnr** [comment]
Likely.  The relevant code might be

````
\documentclass[blockstyle,natbib,reprint]{sigplanconf}
````

**Comment by andygill** [comment]
Dup of #2. Closing.
