### ISSUE TITLE
`legacycopyright` option uses the wrong size for permissions text

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#20]
Turning on the legacycopyright option should use the legacy size for
the copyright space; it doesn't.

**EDIT**: the "size" referred to in the issue is the amount of spaced reserved for copyright text.  This size has been (correctly) reverted in a version change, so this issue can be closed.

The font size of the text itself was not at issue and is considered unimportant.

**Comment by andygill** [comment]
@nrnrnr - is this fixed by turning the size of the box to \tiny, as done in 3.1?

**Comment by MatthewFluet** [comment]
v2.7 and prior use a 1in copyright space; v2.8 uses a 1.2in copyright space; v3.0 uses a 1.5in copyright space (w/ or w/o `legacycopyright` option); v3.1 uses a 1in copyright space (w/ or w/o `legacycopyright` option).  In the absence of yet more options (e.g., explicitly setting the copyright space height or setting a desired version compatibility) there is not a way for `legacycopyright` to reproduce the behavior of both =v2.8 and <=v2.7.

**Comment by nrnrnr** [comment]
Your close message doesn't say how you resolved the issue, so I've reopened it.  Can we consider v2.8 bogus and go with the 1in copyright space?

**Comment by MatthewFluet** [comment]
It's resolved because <=v2.7 use 1in copyright space and v3.1 uses 1in copyright space (and v2.8 doesn't exist and v3.0 was never public, so don't matter for compatibility).

**Comment by MatthewFluet** [comment]
There are differences in the text size of the text in the copyright space.  <=v2.8 use `\scriptsize` while v3.1 uses `\tiny`.  We could use `\if\@legacycopyright \scriptsize \else \tiny \fi`.

But, I remain unclear about the intended purpose of the `legacycopyright` option.  There are other (non-copyright related) changes in the class file that make it nearly impossible to accurately recreate a paper that was written against an earlier version of the class file (e.g., changes in default bib style and punctuation).

**Comment by nrnrnr** [comment]
@MatthewFluet the goal is to make it *possible* to typeset an old paper with the current class.  Changing a few options is OK.

At some point we should start being more aggressive about documenting incompatible changes in the user's guide.   The Haskell Cabal recommendations on version numbering might be useful.

**Comment by MatthewFluet** [comment]
@nrnrnr You haven't clarified whether the original issue is with the copyright space size (i.e., height) or with the copyright space text size (i.e. font size).

With regards to making it _possible_, couldn't one always use `\permission` to recreate whatever copyright text was desired?  Changing copyright space height and copyright space text size require more substantial edits (like redefining `\@copyrightspace` entirely).

**Comment by MatthewFluet** [comment]
If it is just the copyright space text size, then I think that we should close the issue.  An old paper reprinted with the copyright text set in a slightly smaller size (but same space) is a fairly minor difference and wouldn't affect layout, etc. of the rest of the paper.

**Comment by nrnrnr** [comment]
People don't know how to use `\permission` and shouldn't.  I agree that

> An old paper reprinted with the copyright text set in a slightly smaller size (but same space) is a fairly minor difference and wouldn't affect layout, etc. of the rest of the paper.

I've updated the wording of the issue to make it clear that the *space* occupied by the copyright text is what matters and that the problem has been fixed.  Maybe you can fill in the version history at the top?
