### ISSUE TITLE
Usability issues with new `legacycopyright` option

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#22]
With legacycopyright on, `\permission{\ACMUSpermission}` results in a
blank permissions statement.  User error.  Not sure if there is anything to be done here, but worth looking into?

With legacycopyright on, omitting `\permission{...}` results in one of
the new permissions statements, looks like `\publicationrights{licensed}.`
That's not right.

**Comment by andygill** [comment]
Fixed in 3.1.
