### ISSUE TITLE
legacycopyright option allocates too much space on the page, and uses wrong default language

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#23]
The legacy copyright space also has the wrong language and is too big.

     \permission{Your mother wears army boots}

behaves as expected.  So does

    \ACMUSpermission

But the legacy language used in POPL 2011 seems to have gone.
Not a crisis, but I wonder how it happened.

**Comment by andygill** [comment]
What would I use to get/see the legacy language that is referred to? Both examples give expected behavior. How can I make the style file go wrong?

**Comment by andygill** [comment]
@nrnrnr  - I think the spacing was fixed in v3.1, but I'm not sure about the legacy language used in POPL 2011. Can you send me an example, or try 3.1?

**Comment by MatthewFluet** [comment]
The default permission text was changed from v2.6 to v2.7.  The text appearing in v2.6 and earlier corresponds to the copyright text in POPL11 papers on the DL.  v3.1 requires explicitly setting the permission text when using the `legacycopyright` option.
