### ISSUE TITLE
header for sigplanconf.cls should refer to SIGPLAN Info Director

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#24]
Paul's name and email address need to come out of the internal documentation.

People need to be referred to the SIGPLAN Information Director, or if the ID cannot be reached, the SIGPLAN Chair.

Also the header needs to say "don't modify this file; if you have troubles, seek help from the SIGPLAN Information Director."  Or probably some better wording so that the ID is not bombarded with requests for LaTeX help.

This is all stuff we agreed on at our October meeting in Portland.  I'm just getting it down so we don't forget.

**Comment by nrnrnr** [comment]
Some language from Jeremy:

 >   * Program Chairs may be tempted to make changes to the SIGPLAN
 >     LaTeX style sigplanconf.cls. Please don't do this! The style is
 >     carefully considered, and the result of over a decade's discussion
 >     and development. If you have a change request, send it to the
 >     SIGPLAN Information Director <infodir@sigplan.org>. If you
 >     absolutely must change the formatting, define a new class file (eg
 >     myconf1999.cls) that imports sigplanconf.cls, or define a style
 >     file (eg myconf1999.sty) for authors to use in their
 >     papers. Please, UNDER NO CIRCUMSTANCES should you modify the file
 >     sigplanconf.cls and release it onto the internet - that way
 >     lies madness for future conferences!

**Comment by andygill** [comment]
Edited the text above to include correct infodir address infodir_sigplan@acm.org.

**Comment by andygill** [comment]
In v3.1.
