### ISSUE TITLE
Author-year citation style should be the default

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#26]
We voted this in Edinburgh

**Comment by JuliaLawall** [comment]
On Fri, 20 Feb 2015, Norman Ramsey wrote:

> 
> We voted this in Edinburgh

Unfortunately :(

julia

**Comment by nrnrnr** [comment]
@andygill  this issue was slated to be resolved for the Spring release.  Is it?

**Comment by andygill** [comment]
Fixed in v3.1.
