### ISSUE TITLE
Legal text can be set in a smaller font so as to avoid enlarging the "copyright space"

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#27]
Andy,

This is per email from Dirk Beyer, 23 February 2015:

 > we later overwrite the whole copyright box with the correct
 > information but in a smaller font size such that it fits into the
 > space without stretching too much into the bottom margin.

If we could do this, our authors would thank us.

I'd prefer to ask Paul for this in the current milestone, but if it's too much, do change the milestone.

**Comment by andygill** [comment]
Fixed in 3.1.
