### ISSUE TITLE
Add to the users's guide some information about BibTeX

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#28]
We need to steer people toward BibTeX choices that work.  (I don't think we want to get into the BibTeX business.)  Julia Lawall sent this example of something that is broken.  I will diagnose the problem, but something needs to be written into the manual.
![Citation with too much space after "*et al.*"](https://cloud.githubusercontent.com/assets/37659/6647734/1bc90d9c-c9a8-11e4-9584-351e52499a1f.png)

**Comment by nrnrnr** [comment]
The manual should say "don't mess with the `aysep` parameter, and if you must, don't set it to a space.  Use the control sequence `\ ` instead.

**Comment by MatthewFluet** [comment]
Also see #30.
