### ISSUE TITLE
OOPSLA style files

### ISSUE THREAD

**Issue by crista** [SIGPLAN/online#29]
Please see pull request regarding sigplanconf.cls. That's a small change to define a command pertaining to the footer, so that we can call it from the oopsla style files here:
https://github.com/ACM-OOPSLA/Documents

**Comment by nrnrnr** [comment]
As noted on the pull request https://github.com/SIGPLAN/SIGPLAN.github.io/pull/40, at present I don't see the merits of this change.  I'm hoping you'll get back to me either with the information that you don't need this change after all, or with a longer explanation that I will find convincing.

**Comment by MatthewFluet** [comment]
Closing, as the `sigplanconf.cls` file has been retired, and the repository will be archived.
