### ISSUE TITLE
`\doi` is required but undocumented

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#3]
Version 2.8 fails unless the author inserts a `\doi` control sequence.  The sequence and the requirement are undocumented.

**Comment by andygill** [comment]
Fixed in v3.

**Comment by JuliaLawall** [comment]
I don't think I need to receive these any more.

julia

**Comment by andygill** [comment]
I think you need to unfollow SIGPLAN/online. I'll see if I can do it for you.
