### ISSUE TITLE
LaTeX class should probably not force sort-and-compress citations

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#30]
Zhong Shao sent the following bug report to Paul (lightly edited):

>I am working on a camera ready copy of my paper using the sigplanconf.cls file.
>
>I am using the "number" option for the "natbib" package for my citations, but
>the current sigplanconf.cls automatically load the "sort&compress" option,
>which automatically sort all the numbered references in the main text --- I'd
>argue that this is often not what people want.
>
>When I cite a list of papers `\cite{reynolds01,boogie05,htt06}`, I often insist
>on having these references appear in this order, not following some [arbitrary]
>numerical order based on their last names.  In particular,
>it is common that we cite a series
>of work and these citations should be sorted based on their *publication
>dates* (not the first-author's last name as currently imposed by the "sort"
>option).
>
>At the minimum, I'd prefer that sigplanconf offers us an option to disable
>this "sort" option.
>
>Right now I had to modify the sigplanconf file directly in order to remove the
>"sort" option.

What's needed in the next step is some sort of proposal.

**Comment by nrnrnr** [comment]
Proposal: treat this problem as a documentation issue, and tell authors if they don't like the default natbib things, to use the `nonatbib` option and load natbib themselves.

**Comment by MatthewFluet** [comment]
Also see #28.
