### ISSUE TITLE
Consider class option to use uniform numbering for figures and tables

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#33]
Potential change to the style: rather than have, say, Figure 1, Figure 2, Table 1, Figure 3, Table 2, Figure 4, and so on, use one numbering system for both figures and tables, thus:

> Figure 1, Figure 2, Table 3, Figure 4, Table 5, Figure 6

It would be pleasant to make this numbering the default, so as to avoid confusing readers.

The implementation is trivial, so the question is, is it a good idea.

Probably should be held until we have a real advisory board.

**Comment by MatthewFluet** [comment]
Closing, as the `sigplanconf.cls` file has been retired, and the repository will be archived.
