### ISSUE TITLE
the class file conflicts with diagrams.sty

### ISSUE THREAD

**Issue by andygill** [SIGPLAN/online#34]
They both define the macro \@name.

**Comment by adamduracz** [comment]
The following work-around was suggested by Paul Taylor (auhtor of the Diagrams package): substitute an unused name, such as \sigplanconf@name for \@name in sigplanconf.cls.

**Comment by MatthewFluet** [comment]
Closing, as the `sigplanconf.cls` file has been retired, and the repository will be archived.
