### ISSUE TITLE
Conflict with sigplanconf.cls

### ISSUE THREAD

**Issue by lazkany** [SIGPLAN/online#35]
I use a well-known styling file “diagrams.sty” with sigplanconf.cls for writing my paper. it is surprising that there is a conflict between them. i always use “diagrams.sty” for my papers and i never had such a problem.
is there a way to solve this conflict ?

Thank You
![screenshot 2015-06-18 23 01 01](https://cloud.githubusercontent.com/assets/9892259/8258693/46039eb8-16b7-11e5-997d-5feecee25b41.png)

**Comment by andygill** [comment]
Dup of #34.
