### ISSUE TITLE
Adding doi

### ISSUE THREAD

**Issue by andygill** [SIGPLAN/online#36]
Re: the process of editing in the DOI and reference number that comes back from ACM after one has signed the copyright transfer form. 

This wasn't hard to do, but the "Authors' guide" to the style doesn't say how.  Adding a couple of lines describing the relevant commands would be a good idea.

**Comment by nrnrnr** [comment]
I'm pretty sure this stuff is already in.  I'm waiting to hear from  Andrew and will confirm.

I'm thinking of adding a short chapter on workflow.  If we had an advisory board, they could vet it.

**Comment by nrnrnr** [comment]
Confirmed the big four, including `\copyrightdoi`, are documented as of bee244bc0b9e9d979e6e036409cd45e0cabd14d8
