### ISSUE TITLE
Find out what, if anything, needs to be done to support the 2012 classification system

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#37]
What do we put in the author's guide to help authors use http://www.acm.org/about/class/2012 ?

And do we need changes/additions to the style file.

**Comment by JuliaLawall** [comment]
I don't need to be on this mailing list any more.

julia

**Comment by nrnrnr** [comment]
In the context of SPLASH, there

 > was a request why the authors still have to use the old 1998 system of
 > classification. http://www.acm.org/about/class/1998 I asked ACM (I was told
 > before that we need to use the 1998 system until they tell us to switch to
 > the 2012 system) and they told me that the new system can be used as soon
 > as the events switch to the new LaTeX template. Since SIGPLAN has an own
 > template, this does not really apply.

**Comment by nrnrnr** [comment]
@JuliaLawall there is some github setting you will need to change.  I don't know what.  Maybe stop "Watching" this repository?

**Comment by nrnrnr** [comment]
Examples at

mhttp://www.acm.org/publications/article-templates/proceedings-template.html/

**Comment by potanin** [comment]
I would like to be update on the progress on this as we are trying to put together author instructions for SPLASH 2016 right now. Thanks, Alex.

**Comment by nrnrnr** [comment]
@potanin  We're changing over to a new set of volunteers, and to get the new classification system is going to require a new word order from our vendor.  This is unlikely to happen in time for SPLA

**Comment by nrnrnr** [comment]
This issue is now split into #38 and #40 (with #39 being related)
