### ISSUE TITLE
Make contact with Paul A and ask for support for the new ACM classification system

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#38]
Support should be identical to what ACM is mandating for their authors with their style guide.

@MatthewFluet I'm dumping this in your lap and closing #37

**Comment by nrnrnr** [comment]
Examples at http://www.acm.org/publications/article-templates/proceedings-template.html/

**Comment by MatthewFluet** [comment]
Fixed in forthcoming version.
