### ISSUE TITLE
Authors' guide should have a section on workflow

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#41]
This means: what to do at submission time, what to do at camera-ready time.
Basically, what doodads can be ignored on your submission round.
In other words, a section oriented toward authors' needs and not toward the structure of the document.

Norman has promised to write this, and Andrew Black (plus the advisory board) will review it.
But I've pushed it out to a future milestone.

**Comment by MatthewFluet** [comment]
Closing, as the `sigplanconf.cls` file has been retired, and the repository will be archived.
