### ISSUE TITLE
Author's Copies

### ISSUE THREAD

**Issue by adamsmd** [SIGPLAN/online#46]
I see that the `\authorversion` command is now considered legacy, but I don't see how authors are expected to prepare author versions of their papers.  The [ACM Copyright Policy](http://www.acm.org/publications/policies/copyright_policy#Retained) requires a statement "substantially similar" to the following "in connection with any use by the Owner".

 ```© {Owner/Author | ACM} {Year}. This is the author's version of the work. It is posted here for your personal use. Not for redistribution. The definitive Version of Record was published in {Source Publication}, http://dx.doi.org/10.1145/{number}.```

(1) For author versions, is this no longer required to be placed in the copyright space?
(2) If it is still required, what the recommended way for authors to do this?

**Comment by MatthewFluet** [comment]
Fixed in forthcoming version.
