### ISSUE TITLE
One-Column Support

### ISSUE THREAD

**Issue by adamsmd** [SIGPLAN/online#47]
The revision history in sigplanconf.cls claims that one-column support was dropped:

`%  2005.05.06   PCA     1.0     Eliminate 'onecolumn' option.`

However, there is still a lot of code for one-column in sigplanconf.cls though the document-class option for using it is commented out:

`%%%\DeclareOption{onecolumn}{\@setflag \@onecolumn = \@true}`

If one-column is not supported, can we remove the code for one-column?  (I can do the work.  I just need to know if it should be done.)

**Comment by MatthewFluet** [comment]
Fixed in forthcoming version.
