### ISSUE TITLE
DOI/bibliography issue

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#8]
Hi Norman,

Stefan has comments about DOIs in our template. Do you want to answer him?

> Now on to the Latex template: I have noticed some while ago that the
> recent revision of the SIGPLAN proceedings Latex template define the
> "doi" macro that is actually already used by Bibtex if one uses the
> "doi" field in the entries. The redefinition does probably produce
> errors on the command line but generates a regular PDF file. The
> bibliography, however, now contains double periods (e.g., " [....]. .
> [...]") where the DOI URL would normally be rendered. These
> double-periods are just a minor inconvenience, but if not addresses it
> might be that the background job processing PDFs of the ACM DL will
> not be able to cross-reference articles with the same precision as it
> does with the links present. I scanned the POPL'14 proceedings and
> many papers don't even cite the DOI links. This lack could indicate
> problems where authors then just choose to not render DOI links after
> all. On the other hand, it could mean that it is official SIGPLAN
> policy to not render DOI links.
> 
> I have a patched version of the SIGPLAN template such that the DOI
> links as produced by Bibtex are actually included in the bibliography.
> If you think we should fix the problem, I would be happy to contribute
> my patch to SIGPLAN.
> 
> Other than that I hope that everything's swell,
> take care,
> --stefan

**Comment by andygill** [comment]
This is fixed by using \copyrightdoi, as in 3.X.
