### ISSUE TITLE
figure out how deprecated legacy commands should be handled in the manual

### ISSUE THREAD

**Issue by nrnrnr** [SIGPLAN/online#9]
What to do about legacy commands?

- document nothing?

- document the `legacypermissions` class option with some vague language

- document the legacy commands in a section on deprecated commands

- other?

**Comment by MatthewFluet** [comment]
Choosing to document nothing.  Currently, it is only the `legacycopyright` option and related commands and the generated `\@latex@error`s describe how to adapt.
